server:
  name: smart_home_service
  port: 9080
info:
  service-info: smart_home_service
  api-doc: /swagger-ui.html
spring:
    datasource:
        url: jdbc:mysql://localhost:3306/smart_home?allowMultiQueries=true
        username: root
        password: root
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        maxIdle: 8
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
        removeAbandoned : false
        maxPoolPreparedStatementPerConnectionSize : 50
        dialect: MYSQL
mybatis:
  mapper-locations: classpath*:com/atat/soft/**/dao/*.xml
  config-location: /mybatis-config.xml
custom:
  rest:
    connection:
      connection-request-timeout: 3000
      connect-timeout: 3000
      read-timeout: 3000
swagger:
  basePath: com.atat.soft
smsPaltform:
    name: xiaomao258
    pwd: 27221777a
    id: 300
wxPlatform:
  wxAppId: wxe53df1855bab1cc8
  wxSecret: 70f10e2dfd552c39fd4be98c81fd0f0d
  wxWarnModel: L9KbX2H3pprmm2J3c3uh7TAonffAjMqYLMST78BAlmE
#debug: true
